name: deployment

on:
  push:
    branches:
      - prod

env:
  AWS_REGION: us-east-1
  AWS_BUCKET: syene.proximum.xyz

jobs:
  deploy:
    name: Deploy to S3 & CloudFront
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Rust toolchain
        run: |
          rustup update
          rustup target add wasm32-unknown-unknown
      
      - name: Install wasm-pack
        working-directory: web
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          cd rust-proximum-simulation && cargo clean

      - name: Compile Rust to WASM
        working-directory: web
        run: npm run compile-wasm

      - name: Install dependencies (including Rust dependencies)
        working-directory: web
        run: npm install

      - name: Build the project
        working-directory: web
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        working-directory: web
        run: |
          aws s3 sync ./build s3://${{ env.AWS_BUCKET }} --delete

      - name: Create CloudFront invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"