name: deployment

on:
  push:
    branches:
      - prod

env:
  AWS_REGION: us-east-1
  AWS_BUCKET: syene.proximum.xyz
  CLOUDFRONT_DISTRIBUTION_ID: E2HUW0CWB1JIGH

jobs:
  deploy:
    name: Deploy to S3 & CloudFront
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Rust toolchain
        run: |
          rustup update
          rustup target add wasm32-unknown-unknown
          cargo install wasm-pack
          cargo build

      - name: Compile Rust to WASM
        run: npm run compile-wasm

      - name: Install dependencies (including Rust dependencies)
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync ./build s3://${{ env.AWS_BUCKET }} --delete

      - name: Create CloudFront invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"